### ISSUE TITLE
Why is "testthat" in "Imports" and not in "Suggests"?

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#19]
https://github.com/r-hyperspec/hySpc.dplyr/blob/8bd5dc1eef25036a0c14a7e5366cff36f8d653fb/DESCRIPTION#L21

**Comment by cbeleites** [comment]
... because we need to import some of its functions for our `.test<-()` and `hyperSpec.dplyr.unittest()` functions.

I think we may want to put that into a **hySpc.helpers** package, though. That will make it easier to keep the code working similarly across the package zoo.

**Comment by GegznaV** [comment]
Ok. I raised this issue as usually `testthat` is not used directly by users of a package, but just by developers. So it usually goes to Suggests in R packages.

**Comment by cbeleites** [comment]
Dependency to **testthat** will be removed in favor of **hySpc.testthat**: #26
