### ISSUE TITLE
Unit test that fails: expect_error(filter(chondro, spc > 250))

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#20]
https://github.com/r-hyperspec/hySpc.dplyr/blob/6ae23ea0883f0984e304341647ea8cfe8a798c1a/R/filter.R#L78

**Comment by GegznaV** [comment]
I suggest accepting #18 before fixing this issue.

**Comment by cbeleites** [comment]
fixed by 131c7dbe
