### ISSUE TITLE
Arguments .data, res in hy_update_labels must be properly documented

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#21]
https://github.com/r-hyperspec/hySpc.dplyr/blob/94f1c5ec1a757ff26508f18b40ea0d6f241ad37c/R/hy_update_labels.R#L7

**Comment by GegznaV** [comment]
I suggest accepting #18 before fixing this issue.

**Comment by eoduniyi** [comment]
`hy_update_labels` is properly documented going to close this now.
