### ISSUE TITLE
Travis CI status does not arrive

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#22]
@cbeleites, I think we have an issue in `r-hyperspec/hySpc.dplyr` related to how Travis displays the status of continuous integration results (**the status is never updated**):

![image](https://user-images.githubusercontent.com/12725868/84110061-c1819780-aa2c-11ea-91d6-737926738a38.png)

It's a known issue:
>As of October 4th 30, those repositories on travis-ci.com 23 which are managed by GitHub Apps no longer receive updates to the GitHub Commit Status API. Instead, Build Statuses will be posted to the GitHub Check Runs API.

More details and a possible fix is here:
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by cbeleites** [comment]
The original source of such problems in the linked "possible fix" does not apply to us (the settings were correct). However, spurious such issues are reported with no really good solution other than waiting and potentially triggering a new build. 

I (temporarily?) removed the requirement that the branch must pass. 
I'll leave this open until we see whether things work again.

**Comment by cbeleites** [comment]
Seems to be mostly working - only rare timeouts left that are not due to **hySpc.dplyr**.
