### ISSUE TITLE
R-CMD-CHECK fails due to incomplete documentation

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#23]
https://github.com/r-hyperspec/hySpc.dplyr/runs/753435891?check_suite_focus=true

![image](https://user-images.githubusercontent.com/12725868/84139896-61551a80-aa59-11ea-984c-ee9465c3987d.png)

**Comment by cbeleites** [comment]
@eoduniyi, @GegznaV marked some missing documentation with `FIXME` - can you please take care of this?

I think this can safely be done in the develop branch.

**Comment by eoduniyi** [comment]
Fixed the documentation issue going to close now.

**Comment by GegznaV** [comment]
@eoduniyi it would be better if each closed issue would be linked to a pull request/commit that closes the issue. 
Do you know "magical" words 'closes', 'fixes', 'solves' etc. in pull requests that automatically close issues?

**Comment by eoduniyi** [comment]
> @eoduniyi it would be better if each closed issue would be linked to a pull request/commit that closes the issue.
> Do you know "magical" words 'closes', 'fixes', 'solves' etc. in pull requests that automatically close issues?

@GegznaV Thank you will apply from here on out!
