### ISSUE TITLE
Use hySpc.testthat

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec.tidyverse#26]
for the unit tests once it is available on CRAN.

- [x] replace `.test<-()` by `test<-()`
- [x] use `unittest("hySpc.dplyr")` in `tests/testthat/test_attached.R`
- [x] correct library calls in `tests/testthat.R`
- [x] remove old unittest code except the testdata

**Comment by eoduniyi** [comment]
Looking at the development branch of `hySpc.dplyr` I think we have accomplished everything on this list. Going to close now.

**Comment by cbeleites** [comment]
No, the open point about `tests/testthat.R` is still open...

**Comment by cbeleites** [comment]
done now with commit 49df9d9
