### ISSUE TITLE
Provide user-friendly way of loading/attaching the hySpc.* packages

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec.tidyverse#27]
I.e., a function that attaches (amost) all installed packages of the **hySpc.\*** family. 

Exceptions would be 

- **hySpc.testthat** which IMHO shoud not be attached automatically (the more so as **testthat** masks some 
- Should **hySpc.dplyr** be an exception as well? It masks e.g. `stats::filter()` with totally different functionality.
  (but then `filter()` is always a particularly troublesome function, since there's also `signal::filter()`)?

**Comment by cbeleites** [comment]
Sorry, wrong repo, see cbeleites/hyperSpec https://github.com/cbeleites/hyperSpec/issues/218

**Comment by GegznaV** [comment]
I think it is possible to migrate issues between repos. I have seen this kind of behaviour before.

**Comment by GegznaV** [comment]
https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository
