### ISSUE TITLE
Fix unit tests in hySpc.dplyr.unittest()

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec.tidyverse#46]
![image](https://user-images.githubusercontent.com/12725868/111605642-239ed280-87df-11eb-880b-c51a6668efc6.png)

![image](https://user-images.githubusercontent.com/12725868/111606554-03bbde80-87e0-11eb-8261-c810be7e622d.png)

**Comment by GegznaV** [comment]
@eoduniyi can you look into this?

**Comment by eoduniyi** [comment]
> @eoduniyi can you look into this?

@GegznaV sorry for getting back to you so late, but I'm swamped with school atm. I won't be able to contribute reliably for a while.

**Comment by GegznaV** [comment]
It's OK. But, please, return when you have time for this.

**Comment by GegznaV** [comment]
@eoduniyi, could you spend some time to fix these unit-test-related issues?

**Comment by GegznaV** [comment]
This particular issue was fixed several months ago. I forgot to link the related commit but I think it was this one: b69892658435b04d95b1c364ef0e10421280d0ff
