### ISSUE TITLE
fortify `dplyr::mutate`

### ISSUE THREAD

**Issue by cbeleites** [cbeleites/hyperSpec.tidyverse#6]

**Comment by 12VISHESH** [comment]
hey @cbeleites
I found this project "hpersec" very interesting. 
I want to work on this issue!
Already I have completed the easy task and pasted the result as well as the profile link on the home page.
please assign me this issue.
thanks and regards 
Vishesh Tripathi

**Comment by cbeleites** [comment]
@12VISHESH: great, go ahead. Do not hesitate to contact us and ask in case you have questions or doubts.

**Comment by 12VISHESH** [comment]
@cbeleites sir I mailed you already you!
Please have a look and reply for the same
Thanks and regards

**Comment by cbeleites** [comment]
Dear @12VISHESH,
I got your email and had a look at your github repo: that is fine as far as it goes, so easy test: passed :+1: 

But I could not find any concrete question that I can answer?

Also, please rather than emailing me in person, please use the issues here (also please post your introduction on the GSoC issue): that way the other mentors can see and answer your issues and results as well.

**Comment by 12VISHESH** [comment]
@cbeleites 
Thank you for assigning this issue to me .I will start work on this issue and solve this as soon as possible. 
According to your last reply I haven't find gsoc issue where I can introduce my self.
Please Redirect to me on that for the same 

Thanks and regards

**Comment by cbeleites** [comment]
see https://github.com/cbeleites/hyperSpec/issues/99

**Comment by eoduniyi** [comment]
`mutate` and `transmute` for hypeSpec objects have been implemented. Going to close this now.
