### ISSUE TITLE
Wrangling of hyperSpec objects in a `dplyr`-like style

### ISSUE THREAD

**Issue by ximeg** [cbeleites/hyperSpec.tidyverse#8]
When working with data frames, package `dplyr` makes a data wrangling process really easy. One of the particular reasons I like dplyr is that it allows to avoid boilerplating, i.e. repeating the name of a very same variable many times in single command. It also brings clear and elegant syntax. Many of its functions could be logically transferred to `hyperSpec` object, but since it's not a dataframe, it doesn't work. 

### Examples of what I think would be cool:

* Extract observations with `filter`. With convetional subsetting operator, you have to repeat variable name at each comparison operator. Imagine you have a variable called `preproc.normal.chondro_smooth_subset` repeated 4 times?

```r
chondro %>% filter(clusters == "lacuna" & x > 5)  # YES!

# as opposed to
chondro[chondro$clusters == "lacuna" & chondro$x > 5]

# well, you could also do it this way
chondro %>% .[.$clusters == "lacuna" & .$x > 5]
```

* Drop extra data - can be useful when converting into a long dataframe for `ggplot`.

```r
chondro %>% select(filename, clusters) %>% as.long.df  # YES!

# as opposed to
chondro_copy <- chondro
chondro_copy@data <- chondro_copy@data[c("spc", "filename", "clusters")]
chondro_copy %>% as.long.df
```

* Rename extra data column

```r
chondro %>% rename(region = clusters)  # YES!

# as opposed to
chondro$region <- chondro$clusters
chondro$region <- NULL
```

* `Mutate()`, `transmute()`, `between()`

Actually, most of the [functionality provided by `dplyr`](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) is already implemented in `hyperSpec` in some kind of form. But I really would like to see **a more elegant syntax for subsetting and manipulation of the extra data columns.** Don't blame me if I'm just missing something obvious.

**Comment by cbeleites** [comment]
This has been split into smaller issues: #1, #2, #4, #5, #6, #7
